---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: true

- name: Create web directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Copy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart apache
